### ISSUE TITLE
Won't compile on ARM

### ISSUE THREAD

**Issue by totoCZ** [rainycape/governator#1]
I'm trying governator as a supervisord replacement, but it won't compile on armhf due to https://github.com/rainycape/governator/commit/d2e5cbd564084528a445fafc5ec829f5434bcb90

```
# gopkg.in/rainycape/dl.v0
/tmp/go-build944444496/gopkg.in/rainycape/dl.v0/_obj/amd64.o: In function `call':
../go/src/gopkg.in/rainycape/dl.v0/amd64.c:56: undefined reference to `make_call'
collect2: error: ld returned 1 exit status
```

dl probably needs to detect it has no arm support and fail the Open call or governator shouldn't attempt to load it at all.

**Comment by rainycape** [comment]
@TomHetmer Thanks for heads up. This should be fixed now, governator now only uses dl on amd64.
