### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by mpictor** [rainycape/governator#3]
$ `go get github.com/rainycape/governator`

``` no-highlight
package gnd.la/config: unrecognized import path "gnd.la/config" (https fetch: Get https://gnd.la/config?go-get=1: dial tcp 192.99.45.224:443: getsockopt: connection refused)
package gnd.la/log: unrecognized import path "gnd.la/log" (https fetch: Get https://gnd.la/log?go-get=1: dial tcp 192.99.45.224:443: getsockopt: connection refused)
package gnd.la/util/parseutil: unrecognized import path "gnd.la/util/parseutil" (https fetch: Get https://gnd.la/util/parseutil?go-get=1: dial tcp 192.99.45.224:443: getsockopt: connection refused)
package gnd.la/util/stringutil: unrecognized import path "gnd.la/util/stringutil" (https fetch: Get https://gnd.la/util/stringutil?go-get=1: dial tcp 192.99.45.224:443: getsockopt: connection refused)
```

An excellent argument against _not_ pointing at github. Fixable via

``` bash
go get github.com/rainycape/gondola
ln -s $GOPATH/src/github.com/rainycape/gondola $GOPATH/src/gnd.la
go get github.com/rainycape/governator
```

**Comment by drnic** [comment]
I'm getting a variation of the issue:

```
go get github.com/rainycape/governator
package gnd.la/config: unrecognized import path "gnd.la/config" (https fetch: Get https://gnd.la/config?go-get=1: x509: certificate has expired or is not yet valid)
package gnd.la/log: unrecognized import path "gnd.la/log" (https fetch: Get https://gnd.la/log?go-get=1: x509: certificate has expired or is not yet valid)
package gnd.la/util/parseutil: unrecognized import path "gnd.la/util/parseutil" (https fetch: Get https://gnd.la/util/parseutil?go-get=1: x509: certificate has expired or is not yet valid)
package gnd.la/util/stringutil: unrecognized import path "gnd.la/util/stringutil" (https fetch: Get https://gnd.la/util/stringutil?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by JJ** [comment]
Me too. Will have to fork & fix.

**Comment by mpictor** [comment]
It's pretty damned pathetic that @rainycape would go go to the trouble of pushing an alternate distribution method on people, but when it breaks they can't be bothered to maintain it or remove it.

**Comment by JJ** [comment]
I've been checking out the upstream dependency, Gondola, and it's got the self same problem. Plus many files to edit. So I'll just go and use something else, like APM. Will take advice, too, APM is not perfect either...

**Comment by fiam** [comment]
The project is definitely not abandoned, we're using it in production in several places. However, most of its development is happening in our private repo. For this reason, some of the dependencies in the public branch are not working anymore. I've just pushed a couple of commits which replace most of them with working ones.

The only one non-working right now is gnd.la/config, but I'm not sure how I want to replace it (I might just copy the relevant bits from gnd.la/config, since it's just used to parse the service files). I expect to push a fix to the this repo in the next few days.

**Comment by fiam** [comment]
@mpictor I'm deleting your last comment, since it doesn't add anything remotely useful to the conversation.

**Comment by mpictor** [comment]
I can't say that I'm terribly impressed that you deleted my (admittedly critical) comment, but I am glad to see that you are fixing the problem.

Saying this package is not abandoned is somewhat misleading when, as you note, recent development is happening in a private repo and those changes hadn't trickled down to this one.

In the future, please, _please_, **please** do not make your packages dependent on your own infrastructure unless you can commit to maintaining that infrastructure for a long time and in a timely manner! :smile:

**Comment by fiam** [comment]
I've just fixed the problems with the gnd.la repository, which makes governator go-getable again. Eventually, I'd like to remove the dependency on Gondola, but refactoring gnd.la/config outside of the framework right now seems like too much work in exchange the benefits it would provide.
